version: '3.8'

services:
  heterogeneous-architecture:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./config:/home/app/config
      - ./models:/home/app/models
    environment:
      - RUST_LOG=info
      - ENV=production
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional GPU service (for CUDA-enabled containers)
  gpu-service:
    build: .
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    environment:
      - CUDA_VISIBLE_DEVICES=all
    restart: unless-stopped

networks:
  default:
    name: heterogeneous-network