# Application Configuration
app:
  name: "My Python Application"
  version: "1.0.0"
  debug: true
  
server:
  host: "localhost"
  port: 8000
  workers: 4
  
database:
  host: "localhost"
  port: 5432
  name: "myapp_db"
  user: "myapp_user"
  
logging:
  level: "INFO"
  file: "../log/application.log"